#!/usr/bin/env python

import hy
import sys

from main import main

if __name__ == "__main__":
    if len(sys.argv) == 2:
        cmd, ip = sys.argv
        port = 9000
    else:
        cmd, ip, port = sys.argv
    main(server_ip=ip, port=port)
